### ISSUE TITLE
prepare for seminar

### ISSUE THREAD

**Issue by kmouleejunhyuk** [kmouleejunhyuk/MarchHare#3]
prepare seminar for milestone.

**Comment by JiyouSeo** [comment]
Will be presented in seminar
1. Data Representation in 3D Space(Implicit, Explicit Representation) 
2. Camera Calibration(Intrinsic, Extrinsic parameter)
3. NeRF: Representing Scenes as Neural Radiance Fields for View Synthesis

**Comment by kmouleejunhyuk** [comment]
seminar date: (KST)20221211 
topic: survey of NERF & Joint optimization of topology, materials and lighting from multi-view image observations
issue closed
